server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-relzl6gk.sql.tencentcdb.com:28656/dynmap?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: dynmap
    password: dynmap@666
    driver-class-name: com.mysql.cj.jdbc.Driver
